# Generated by Django 3.2 on 2023-07-13 07:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_name_room_room_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='time',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='Team', to='app.timing'),
        ),
    ]
